services:
  # Laravel PHP service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./projects/voting:/www/wwwroot/laravel-docker-setup/projects/voting
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - DB_CONNECTION=${DB_CONNECTION:-pgsql}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-secret}

  # Web (Nginx) service
  web:
    image: nginx:stable-alpine
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./projects/voting:/www/wwwroot/laravel-docker-setup/projects/voting
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro

  # PostgreSQL service
  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Expose PostgreSQL port directly for database tools
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_DB=${DB_DATABASE:-laravel}
      - POSTGRES_USER=${DB_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}

  # PgAdmin service
  pgadmin:
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
      - PGADMIN_LISTEN_PORT=80

  # Node.js service for frontend development
  node:
    image: node:18-alpine
    ports:
      - "${NODE_PORT:-5173}:5173"
    volumes:
      - ./projects/voting:/www/wwwroot/laravel-docker-setup/projects/voting
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-true}
    command: >
      sh -c "npm install && npm run dev"
